version: '2'
services:
  sql-tables-example-api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
     - "8282:8282"
    environment:
     - API_PORT=8282
     - DB_USER=sql-tables-example
     - DB_NAME=sql-tables-example
     - DB_PASS=this-is-dev
     - DB_HOST=postgres
     - DB_PORT=5432
    depends_on:
     - "postgres"
    volumes:
     - ../:/opt/sql-tables:ro
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: this-is-dev
      POSTGRES_USER: sql-tables-example
      POSTGRES_DB: sql-tables-example
